version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rss-api
    environment:
      - MONGO_URL=mongodb://rss-mongo:27017/rss-api
      - PORT=3000
      - NODE_ENV=production
    links:
      - "mongo"
    depends_on:
      - "mongo"
    networks:
      - rss-api-network

  web-server:
    image: nginx:alpine
    container_name: rss-nginx
    ports:
      - 80:80
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    links:
      - "api"
    networks:
      - rss-api-network

  mongo:
    image: mongo:latest
    container_name: rss-mongo
    ports:
      - 27017:27017
    networks:
      - rss-api-network

networks:
  rss-api-network:
